### ISSUE TITLE
SAML SLO with post binding not hitting IDP

### ISSUE THREAD

**Issue by gtiwari2015** [rasmusson/OpenSAML-sample-code#3]
Hi ,
I am trying to do SLO using post binding Signed request to IDP (OkTA ) and  am following your opensaml-signing and verififcation project to send Post signed request to SLO url of OKTA IDP
but i can see in the logs its not triggering any call to OKTA , and okta logs showing the same.
Please advise .

**Comment by gtiwari2015** [comment]
Also just curious regarding the use of velocity engine , i have webapplication in react which doesnt need any other html page apart from existing pages in react.

**Comment by rasmusson** [comment]
Oh dear, this one was i the social folder in gmail... Did you resolve it?
